// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BinsteamProjectSystem.Entities;

public partial class Country
{
    [Key]
    [StringLength(2)]
    [Unicode(false)]
    public string CountryCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CountryName { get; set; }
}