// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BinsteamProjectSystem.Entities;
using Microsoft.EntityFrameworkCore;

namespace BinsteamProjectSystem.DAL;

public partial class StarTED_TestContext : DbContext
{
    public StarTED_TestContext(DbContextOptions<StarTED_TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<ClubActivity> ClubActivities { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<GradeAssignment> GradeAssignments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentID).HasName("PK_dbo.Assignments");
        });

        modelBuilder.Entity<ClubActivity>(entity =>
        {
            entity.HasKey(e => e.ActivityID).HasName("PK_dbo.ClubActivities");

            entity.ToTable(tb => tb.HasTrigger("Trigger_ClubActivities_CampusVenue"));
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryCode).HasName("PK_dbo.Countries");

            entity.Property(e => e.CountryCode).IsFixedLength();
        });

        modelBuilder.Entity<GradeAssignment>(entity =>
        {
            entity.HasKey(e => e.GradeID).HasName("PK_dbo.GradeAssignments");

            entity.HasOne(d => d.Assignment).WithMany(p => p.GradeAssignments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.GradeAssignments_dbo.Assignments_AssignmentID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}